<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <SelfContained>false</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Title>MRPORT</Title>
    <Description>MRPORT-过检测</Description>
    <Version>1.0.0.0</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="8.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="WinDivert.dll" CopyToOutputDirectory="PreserveNewest" Condition="Exists('WinDivert.dll')" />
    <Content Include="WinDivert64.sys" CopyToOutputDirectory="PreserveNewest" Condition="Exists('WinDivert64.sys')" />
  </ItemGroup>

</Project>
